# This is a basic workflow to help you get started with Actions
name: "Build and test"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - release/**
      - master
      - dev
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: "7.1"
            illuminate: "5.5.*"
            orchestra: "3.5.*"
            phpunit: "6.*"
          - php-version: "7.1"
            illuminate: "5.6.*"
            orchestra: "3.6.*"
            phpunit: "7.*"
          - php-version: "7.1"
            illuminate: "5.6.*"
            orchestra: "3.6.*"
            phpunit: "7.*"
          - php-version: "7.1"
            illuminate: "5.7.*"
            orchestra: "3.7.*"
            phpunit: "7.*"
          - php-version: "7.1"
            illuminate: "5.8.*"
            orchestra: "3.8.*"
            phpunit: "7.*"
          - php-version: "7.2"
            illuminate: "5.5.*"
            orchestra: "3.5.*"
            phpunit: "6.*"
          - php-version: "7.2"
            illuminate: "5.6.*"
            orchestra: "3.6.*"
            phpunit: "7.*"
          - php-version: "7.2"
            illuminate: "5.7.*"
            orchestra: "3.7.*"
            phpunit: "7.*"
          - php-version: "7.2"
            illuminate: "5.8.*"
            orchestra: "3.8.*"
            phpunit: "7.*"
          - php-version: "7.2"
            illuminate: "6.*"
            orchestra: "4.*"
            phpunit: "8.*"
          - php-version: "7.2"
            illuminate: "7.*"
            orchestra: "5.*"
            phpunit: "8.*"
          - php-version: "7.3"
            illuminate: "5.8.*"
            orchestra: "3.8.*"
            phpunit: "8.*"
          - php-version: "7.3"
            illuminate: "6.*"
            orchestra: "4.*"
            phpunit: "8.*"
          - php-version: "7.3"
            illuminate: "7.*"
            orchestra: "5.*"
            phpunit: "8.*"
          - php-version: "7.3"
            illuminate: "8.*"
            orchestra: "6.*"
            phpunit: "8.*"
          - php-version: "7.4"
            illuminate: "7.*"
            orchestra: "5.*"
            phpunit: "8.*"
          - php-version: "7.4"
            illuminate: "8.*"
            orchestra: "6.*"
            phpunit: "8.*"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release/support-square-sdk

      # Setup php
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      # Runs a set of commands using the runners shell
      - name: "Building and testing accross multiple environments"
        env:
          ILLUMINATE_VERSION: ${{ matrix.illuminate }}
          ORCHESTRA_TESTBENCH_VERSION: ${{ matrix.orchestra }}
          PHPUNIT_VERSION: ${{ matrix.phpunit }}
          PHP_VERSION: ${{ matrix.php-version }}
        run: |
          composer require illuminate/config:${ILLUMINATE_VERSION} --no-update
          composer require illuminate/console:${ILLUMINATE_VERSION} --no-update
          composer require illuminate/contracts:${ILLUMINATE_VERSION} --no-update
          composer require illuminate/container:${ILLUMINATE_VERSION} --no-update
          composer require illuminate/database:${ILLUMINATE_VERSION} --no-update
          composer require --dev orchestra/testbench:${ORCHESTRA_TESTBENCH_VERSION} --no-update
          composer require --dev phpunit/phpunit:${PHPUNIT_VERSION} --no-update
          if [[ "${PHP_VERSION}" == "7.1" ]]; then composer remove square/square --no-update; composer install square/connect@3.20200528.1 --no-update; fi;
          if [[ "${ILLUMINATE_VERSION}" == "5.5.*" || "${ILLUMINATE_VERSION}" == "5.6.*" || "${ILLUMINATE_VERSION}" == "5.7.*" || "${ILLUMINATE_VERSION}" == "5.8.*" ]]; then composer remove --dev fakerphp/faker; composer require --dev "fzaninotto/faker:^1.4" --no-update; fi;
          if [[ "${ILLUMINATE_VERSION}" == "8.*" ]]; then composer require --dev "laravel/legacy-factories:^1.0.4" --no-update; fi;